Add vimeo param
heimrichhannot/contao-video-bundle pull request #18
Opened 2023-08-21 08:52 UTC by zonky2

With the customization it is possible to pass additional Vimeo parameters in the input field as well

2023-08-22 09:01 UTC, koertho requested changes
I think this is a good solution. Please see my comment on the dca changes.

2023-08-22 09:06 UTC, zonky2 commented on src/Resources/contao/dca/tl_content.php
> +$arrFields['vimeo']['sql'] = "varchar(128) NOT NULL default ''";
you mean here https://github.com/heimrichhannot/contao-video-bundle/blob/8d2fbf4d97cdf256619cb37765bb18363ad9e23e/src/Generator/DcaFieldGenerator.php#L74 ?

2023-08-22 10:16 UTC, koertho commented on src/Resources/contao/dca/tl_content.php
> +$arrFields['vimeo']['sql'] = "varchar(128) NOT NULL default ''";
I would do it after the variable initiation somewhere here: https://github.com/heimrichhannot/contao-video-bundle/blob/8d2fbf4d97cdf256619cb37765bb18363ad9e23e/src/Generator/DcaFieldGenerator.php#L279

2023-08-23 14:44 UTC, koertho approved these changes

2023-08-23 14:45 UTC, merged

2023-08-23 14:48 UTC, koertho commented
Thanks @zonky2 ! Your changes are live in version 1.4.0.